### ISSUE TITLE
Could not find artifact org.eclipse.rdf4j:rdf4j-runtime:jar:3.7.4 in jitpack.io

### ISSUE THREAD

**Issue by rbngz** [Interactions-HSG/wot-td-java#64]
When importing the library through Maven, the following error will occur upon executing a `mvn clean install` or `mvn -U test` command:

```
Error:  Failed to execute goal on project tapas-executor-3: Could not resolve dependencies for project ch.unisg.tapas:tapas-executor-3:jar:0.0.1-SNAPSHOT: Could not find artifact org.eclipse.rdf4j:rdf4j-runtime:jar:3.7.4 in jitpack.io (https://jitpack.io) -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
Error: Process completed with exit code 1.
```

I believe this error is caused by this line which will use the specified Build repository for all dependencies.
https://github.com/Interactions-HSG/wot-td-java/blob/a8d5c864770a4289ed6e9cfec8428c9e8fc9fd7c/build.gradle#L54

However, I also tried using the Maven central repository to retrieve the runtime artifact. This will also result in this error despite the fact that the repository should contain the artifact according to [this](https://mvnrepository.com/artifact/org.eclipse.rdf4j/rdf4j-runtime):
```
[ERROR] Failed to execute goal on project tapas-executor-3: Could not resolve dependencies for project ch.unisg.tapas:tapas-executor-3:jar:0.0.1-SNAPSHOT: Could not find artifact org.eclipse.rdf4j:rdf4j-runtime:jar:3.7.4 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

To reproduce:
**pom.xml**
```xml
<repositories>
    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>
</repositories>
```
```xml
<dependency>
    <groupId>com.github.Interactions-HSG</groupId>
    <artifactId>wot-td-java</artifactId>
    <version>v0.1.0</version>
</dependency>
```
Run `mvn clean install`

@andreiciortea @

**Comment by andreiciortea** [comment]
Hi Ruben,

Thanks for finding this issue.

This is a problem with transitive dependencies and Maven (Gradle handles transitive dependencies automatically).

I will push a fix soon and I will bump the library version from v0.1.0 to v0.1.1 (will update the README as well). Please use v0.1.1 with JitPack and all should be fine.

Best,
Andrei
