### ISSUE TITLE
No option to retrieve headers from TDHttpResponse

### ISSUE THREAD

**Issue by rbngz** [Interactions-HSG/wot-td-java#67]
Hello @andreiciortea 

The leubot-API only returns the API key within the response header after calling the `/user` POST endpoint. However, when using the `wot-td-java`-library, there is no option to retrieve headers from the underlying HTTP response since the actual response is marked as `private` and there is no method to retrieve it.

https://github.com/Interactions-HSG/wot-td-java/blob/a7a19f7361dec20596af1a111aa64589940124d7/src/main/java/ch/unisg/ics/interactions/wot/td/clients/TDHttpResponse.java#L32

**Comment by rbngz** [comment]
BTW: Should there not also be a `logOut`-`ActionAffordance` within the Leubot TD since there is a corresponding `DELETE` method possibility at the `/user`-endpoint?

**Comment by danaivach** [comment]
Hi Ruben, we are working on adding a `public` method for retreaving the headers from `TDHttpResponse`. 

Regarding the `DELETE` method, the library is not currently supporting URI templates ( e.g. for handling the URL path for /delete). This feature will be added in the future.

**Comment by andreiciortea** [comment]
Hi @rbngz ,

Indeed, as @danaivach mentioned, URI variables (required to delete an operator) are not currently supported. For the ASSE assignments, we will have to handle the API tokens manually (i.e., outside of the application). We can elaborate on this point tomorrow during the exercise session. ;-)

Let's keep this issue open until we add the missing features.

**Comment by rbngz** [comment]
@danaivach  It seems to me as if the library is perfectly able to issue `DELETE`-requests if the corresponding TD contains such and ActionAffordance.

https://github.com/Interactions-HSG/wot-td-java/blob/3cd1c8e0e6beeb106225db2b975eb59803949577/src/main/java/ch/unisg/ics/interactions/wot/td/clients/TDHttpRequest.java#L49-L52

My question is more related to why there is no such action affordance in this [TD](http://yggdrasil.interactions.ics.unisg.ch/environments/61/workspaces/102/artifacts/leubot1), even though there is such an endpoint available in the API documentation.

Could easily be solved by adding the following ActionAffordance to the TD:
```
[ a <https://ci.mines-stetienne.fr/kg/ontology#LogOut>, td:ActionAffordance;
      td:name "logOut";
      dct:title "Log Out";
      td:hasForm [
          htv:methodName "DELETE";
          hctl:hasTarget <https://api.interactions.ics.unisg.ch/leubot1/v1.3.4/user>;
          hctl:forContentType "application/json";
          hctl:hasOperationType td:invokeAction
        ];
```

**Comment by rbngz** [comment]
@andreiciortea Okay now I understand.. The user id needs to be passed as URI parameter for the deletion and the library is not yet able to build such URI strings. Thank you for the clarification!

**Comment by danaivach** [comment]
Hi Ruben, 

Due to @JeremyLemee, `TDHttpResponse` now features a method `getHeaders()`, and `TDCoapResponse` a method `getOptions()`, respectively. Both methods return a `Map<String, String>` from which you can retrieve the response headers/options. 

I`m going to close the issue since it addresses response header retrieval.

URI templates for enabling a  `logOut`- `ActionAffordance` on leubot, should be addressed on a future RP. My apologies for the inconvenience!

**Comment by rbngz** [comment]
Hello @danaivach 

Thank you! Could you also push this change to jitpack.io?

**Comment by andreiciortea** [comment]
Hi @rbngz ,

Yes, that's correct: the feature for working with URI variables includes reading, writing, and interpreting TDs with URI templates (cf. RFC 6670) and it's not yet ready to be merged into master — but should be soon. ;-)

To get the latest updates for the TD library via JitPack, please use `master-SNAPSHOT` as the version (and this should always point to the latest commit on master).

Thanks Ruben for your input!
