### ISSUE TITLE
Incorrect Argument types for Security Scheme

### ISSUE THREAD

**Issue by rbngz** [Interactions-HSG/wot-td-java#68]
The following [snippet](https://github.com/Interactions-HSG/wot-td-java/blob/f2a958e7020334c9429630e2142650c844e8d873/README.md?plain=1#L256) from the README will throw an error:
```java
Optional<SecurityScheme> securityScheme = td.getFirstSecuritySchemeByType(WoTSec.APIKeySecurityScheme);
if (securityScheme.isPresent()) {
  request.setAPIKey(securityScheme.get(), token);
}
```
The method that is used here (`request.setAPIKey()`) requires an object of type `APIKeySecurityScheme` as first parameter. Instead, an object of type `SecurityScheme` is passed to the method call.

https://github.com/Interactions-HSG/wot-td-java/blob/a7a19f7361dec20596af1a111aa64589940124d7/src/main/java/ch/unisg/ics/interactions/wot/td/clients/TDHttpRequest.java#L67

Since the `APIKeySecurityScheme`-class extends the `SecurityScheme`-class, this can simply be casted when passing the argument to the method call. Therefore I propose the following adjustment to the snippet in the README:

```java
if (securityScheme.isPresent()) {
  request.setAPIKey((APIKeySecurityScheme) securityScheme.get(), token);
}
```
@andreiciortea

**Comment by danaivach** [comment]
Thank you, Ruben. I`ve updated the README file.
