### ISSUE TITLE
Symbols { and } in URI Variables

### ISSUE THREAD

**Issue by JeremyLemee** [Interactions-HSG/wot-td-java#96]
The two symbols { and }, appearing in URI Variables, cannot be read or written by the library. Instead, they are converting respectively to %7B and %7D. This causes a problem when trying to convert the URI template to a proper URI since the conversion algorithm requires the symbols { and }. For that reason, the conversion does not happen.

**Comment by danaivach** [comment]
Fixed by 329f4784d08bc0054e500ec25c6181d6f9d09285
